### ISSUE TITLE
server crashed

### ISSUE THREAD

**Issue by dotopstory** [Titousensei/bluesaga#4]
This error occurs when I run the server. (Tested on Windows, Centos)

```
java.lang.NullPointerException
	at data_handlers.ability_handler.Ability.<init>(Ability.java:82)
	at creature.Creature.<init>(Creature.java:223)
	at creature.Npc.<init>(Npc.java:102)
	at utils.ServerGameInfo.load(ServerGameInfo.java:180)
	at network.Server.start(Server.java:141)
	at game.BPserver.main(BPserver.java:40)
```

public Ability(Ability copy) {
    id = **copy**.id; // copy is NULL
    name = copy.name;
    ....
}

**Comment by Titousensei** [comment]
Can you give a little more details? What command do you use to start the server? Did you create your own map and config?

**Comment by dotopstory** [comment]
I didn't create anything of my own.
I just followed HOWTO.md
like
1. cd SERVER
2. ant
3. ./run -dev

os: Centos 7 x64

**Comment by Titousensei** [comment]
I see, the HOWTO is wrong. I change the options to be able to run different maps and configs, and forgot to update the documentation. The right command to run the classic map is:
  ./run config_classic/

**Comment by dotopstory** [comment]
okay, now it's works. but i've another problem.
i think some files are missing like statuseffects.txt
that one i made then solved.
and  i changed "AreaItem" to "AreaItems" in AreaEffectBuilder.java.
I modified both of these, and the server runs normally. But another error is annoying.

```
[Builder] ERROR - New entry exception in config_classic\shops_classic.txt:18 - java.lang.StackOverflowError
[Builder] ERROR - New entry exception in config_classic\shops_classic.txt:46 - java.lang.StackOverflowError
[Builder] ERROR - New entry exception in config_classic\shops_classic.txt:54 - java.lang.StackOverflowError
[Builder] ERROR - New entry exception in config_classic\shops_classic.txt:57 - java.lang.StackOverflowError
[Builder] ERROR - New entry exception in config_classic\shops_classic.txt:60 - java.lang.StackOverflowError
[Builder] ERROR - New entry exception in config_classic\shops_classic.txt:64 - java.lang.StackOverflowError
[Builder] ERROR - New entry exception in config_classic\shops_classic.txt:67 - java.lang.StackOverflowError
[Builder] ERROR - New entry exception in config_classic\shops_classic.txt:71 - java.lang.StackOverflowError
[Builder] ERROR - New entry exception in config_classic\shops_classic.txt:75 - java.lang.StackOverflowError
```
